---
title             : "Reanalyis of experiment one of Mehr S, Song L, and Spelke E 2016"
shorttitle        : "Melody Test"

author: 
  - name          : "Shawn"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "619 Ave L"
    email         : "sv942@hunter,cuny.edu"

affiliation:
  - id            : "1"
    institution   : "Brooklyn College"

bibliography      : ["r-references.bib","myreferences.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---
    
    
```{r setup, include = FALSE}
library("papaja")
```

```{r}

library(data.table)
all_data <- fread("https://raw.githubusercontent.com/CrumpLab/statisticsLab/master/data/MehrSongSpelke2016.csv")


library(dplyr)
library(ggplot2)

experiment_one <- all_data %>% filter(exp1==1)

baseline <- experiment_one$Baseline_Proportion_Gaze_to_Singer
testphase <- experiment_one$Test_Proportion_Gaze_to_Singer

t.test(testphase, baseline, paired = TRUE)


```
###Table of means 

```{r}
means <- experiment_one %>%
  group_by(Baseline_Proportion_Gaze_to_Singer, Test_Proportion_Gaze_to_Singer)%>%
  summarize(meanbaseline = mean(baseline_proportion_gaze_to_singer),
            meantest = mean(test_proportion_gaze_to_singer))

knitr::kable(means)







```
###Graph 

```{r}
Phase <- rep(c("Baseline","Testphase"), each = 32)
Proportions <- c(baseline,testphase)
plot_df <- data.frame(Phase,Proportions)

library(ggplot2)

mean_df <- aggregate(Proportions ~ Phase, plot_df, mean)

ggplot(plot_df, aes(x=Phase, y=Proportions))+ 
  geom_bar(data=mean_df, stat="identity",aes(fill=Phase))+
  geom_point()

```






###Reanalysis results

We find here that on average, babies looked at the familiar song singer 7% longer than they had in the test condition. This is the same as the results found in the original experiment.

